# Generated by Django 3.0.5 on 2020-04-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_citty_country_scholarship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={},
        ),
    ]
